AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  AuditAWSAccountEmail:
    Type: String
    Default: ""
  LogArchiveAWSAccountEmail:
    Type: String
    Default: ""
  Domain:
    Type: String
  Subdomain:
    Type: String
  IncludeBudget:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeControlTower:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeGuardDuty:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeSecurityHub:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeBackup:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeServiceControlPolicies:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeRootMail:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  TemplateUrlPrefix:
    Type: String

Conditions:
  IncludeBudget: !Equals [ !Ref IncludeBudget, true ]
  IncludeControlTower: !Equals [ !Ref IncludeControlTower, true ]
  IncludeGuardDuty: !And
    - !Condition IncludeControlTower
    - !Equals [ !Ref IncludeGuardDuty, true ]
  IncludeRootMail: !Equals [ !Ref IncludeRootMail, true ]
  IncludeSecurityHub: !And
    - !Condition IncludeControlTower
    - !Equals [ !Ref IncludeSecurityHub, true ]
  IncludeBackup: !And
    - !Condition IncludeControlTower
    - !Equals [ !Ref IncludeBackup, true ]
  IncludeServiceControlPolicies: !And
    - !Condition IncludeControlTower
    - !Equals [ !Ref IncludeServiceControlPolicies, true ]
  GenerateAuditAWSAccountEmail: !And
    - !Condition IncludeRootMail
    - !Equals [ !Ref AuditAWSAccountEmail, "" ]
  GenerateLogArchiveEmail: !And
    - !Condition IncludeRootMail
    - !Equals [ !Ref LogArchiveAWSAccountEmail, "" ]

Resources:

  Budget:
    Condition: IncludeBudget
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/budget.yaml

  ControlTower:
    Condition: IncludeControlTower
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/control-tower.yaml
      Parameters:
        AuditAWSAccountEmail: !If
          - GenerateAuditAWSAccountEmail
          - !GetAtt GeneratedAuditAWSAccountEmail.email
          - !Ref AuditAWSAccountEmail
        LogArchiveAWSAccountEmail: !If
          - GenerateLogArchiveEmail
          - !GetAtt GeneratedLogArchiveAWSAccountEmail.email
          - !Ref LogArchiveAWSAccountEmail

  GeneratedAuditAWSAccountEmail:
    Condition: GenerateAuditAWSAccountEmail
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt GenerateLogAndOrAuditEmailCustomResource.Arn

  GeneratedLogArchiveAWSAccountEmail:
    Condition: GenerateLogArchiveEmail
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt GenerateLogAndOrAuditEmailCustomResource.Arn

  GenerateLogAndOrAuditEmailCustomResource:
    Condition: IncludeRootMail
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 200
      Handler: index.handler
      Runtime: python3.7
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !GetAtt RootMail.Outputs.EmailGeneratorFunction
      InlineCode: !Sub |
        import boto3
        import cfnresponse
        import json

        lambda_client = boto3.client("lambda")

        CREATE = 'Create'
        DELETE = 'Delete'
        UPDATE = 'Update'

        def exception_handling(function):
            def catch(event, context):
                try:
                    function(event, context)
                except Exception as e:
                    print(e)
                    print(event)
                    cfnresponse.send(event, context, cfnresponse.FAILED, {})

            return catch

        @exception_handling
        def handler(event, context):
            RequestType = event["RequestType"]
            Properties = event["ResourceProperties"]
            LogicalResourceId = event["LogicalResourceId"]
            PhysicalResourceId = event.get("PhysicalResourceId")

            print('RequestType: {}'.format(RequestType))
            print('PhysicalResourceId: {}'.format(PhysicalResourceId))
            print('LogicalResourceId: {}'.format(LogicalResourceId))

            id = PhysicalResourceId

            data = {}

            if RequestType == CREATE or RequestType == UPDATE:
              lambda_response = lambda_client.invoke(
                FunctionName='${RootMail.Outputs.EmailGeneratorFunction}'
              )

              response_json = json.loads(lambda_response['Payload'].read().decode('utf-8'))
              data['email'] = response_json['email']

            cfnresponse.send(event, context, cfnresponse.SUCCESS, data, id)

  GuardDuty:
    Condition: IncludeGuardDuty
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/guardduty.yaml

  RootMail:
    Condition: IncludeRootMail
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/rootmail.yaml
      Parameters:
        Domain: !Ref Domain
        Subdomain: !Ref Subdomain

  SecurityHub:
    Condition: IncludeSecurityHub
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/security-hub.yaml

  Backup:
    Condition: IncludeBackup
    Type: AWS::CloudFormation::Stack
    DependsOn: ControlTower
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/backup.yaml

  ServiceControlPolicies:
    Condition: IncludeServiceControlPolicies
    Type: AWS::CloudFormation::Stack
    DependsOn: ControlTower
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/service-control-policies.yaml
      Parameters:
        IncludeSecurityHub: !Ref IncludeSecurityHub
        IncludeBackup: !Ref IncludeBackup

Outputs:

  RootMailDelegationTarget:
    Condition: IncludeRootMail
    Description: Nameservers for the hosted zone delegation
    Value: !GetAtt RootMail.Outputs.DelegationTarget
